version: "3"
services:
  llocsdebegur:
    container_name: llocsdebegur
    build: .
    image: llocsdebegur:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: llocsdebegurDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - llocsdebegur
    depends_on:
      - llocsdebegurDB

  llocsdebegurDB:
    container_name: llocsdebegurDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - llocsdebegur-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - llocsdebegur

  llocsdebegurAdminer:
    container_name: llocsdebegurAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=llocsdebegurDB
    networks:
      - llocsdebegur
    depends_on:
      - llocsdebegurDB

volumes:
  llocsdebegur-data:

networks:
  llocsdebegur:
    name: Llocs-de-begur
    driver: bridge
