version: "3"
services:
  llocs-de-begur:
    container_name: llocs-de-begur
    build: .
    image: llocs-de-begur:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: llocs-de-begurDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - llocs-de-begur
    depends_on:
      - llocs-de-begurDB

  llocs-de-begurDB:
    container_name: llocs-de-begurDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - llocs-de-begur-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - llocs-de-begur

  llocs-de-begurAdminer:
    container_name: llocs-de-begurAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=llocs-de-begurDB
    networks:
      - llocs-de-begur
    depends_on:
      - llocs-de-begurDB

volumes:
  llocs-de-begur-data:

networks:
  llocs-de-begur:
    name: Llocs-de-begur
    driver: bridge
