version: "3"
services:
  llocsdebegur:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports: !reset []
    labels:
      caddy: cms.llocsdebegur.s.mauriciabad.com
      caddy.reverse_proxy: "{{upstreams 1337}}"
    networks:
      - caddy

  llocsdebegurDB:
    ports: !reset []

  llocsdebegurAdminer:
    ports: !reset []
    networks:
      - caddy
    labels:
      caddy: db.llocsdebegur.s.mauriciabad.com
      caddy.reverse_proxy: "{{upstreams 9090}}"

networks:
  caddy:
    name: caddy
    external: true
