name: Deploy backend

on: push

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create backend .env file
        run: echo "${{ secrets.BACKEND_PROD_ENV_FILE }}" > ./backend/.env

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.BACKEND_USERNAME }}
          SSH_KEY: ${{ secrets.BACKEND_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.BACKEND_HOST }}

      - name: Run deploy script
        run: ssh server '/home/shared/llocsdebegur/backend/ghactions-deploy.sh'
