name: Deploy backend

on: push

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create backend .env file
        run: echo "${{ secrets.BACKEND_PROD_ENV_FILE }}" > ./backend/.env

      - name: Deploy to server
        uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: 89.58.2.185
          ssh_user: ghactions
          ssh_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          compose_file: backend/docker-compose.yaml
          pull: true
          build: true
