name: Deploy backend

on: push

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create backend .env file
        run: echo "${{ secrets.BACKEND_PROD_ENV_FILE }}" > ./backend/.env

      - name: Deploy to server
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ghactions@89.58.2.185
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          stack_file_name: backend/docker-compose.yaml
          args: up -d
          deploy_path: /home/ghactions/llocs-de-begur
