name: Deploy backend

on: push

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create backend .env file
        run: echo "${{ secrets.BACKEND_PROD_ENV_FILE }}" > ./backend/.env

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}

      - run: DOCKER_HOST=ssh://ghactions@89.58.2.185 docker compose -f backend/docker-compose.yaml up
