name: Test backend

on: push

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  health-check:
    runs-on: ubuntu-latest
    name: Health check backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

      - name: Create backend .env file
        run: echo "${{ secrets.BACKEND_PROD_ENV_FILE }}" > ./backend/.env

      - name: Check services healthiness
        if: steps.filter.outputs.backend == 'true'
        uses: thegabriele97/dockercompose-health-action@main
        with:
          timeout: '60'
          workdir: 'backend'
