name: Test backend

on: push

jobs:
  health-check:
    runs-on: ubuntu-latest
    name: Health check backend
    steps:
      - name: Check services healthiness
        uses: thegabriele97/dockercompose-health-action@main
        with:
          timeout: '60'
          workdir: 'backend'
