name: Test backend

on: push

jobs:
  health-check:
    runs-on: ubuntu-latest
    name: Health check backend
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend: 
              - 'backend/**'

      - name: Check services healthiness
        if: steps.changes.outputs.backend == 'true'
        uses: thegabriele97/dockercompose-health-action@main
        with:
          timeout: '60'
          workdir: 'backend'
